services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - fastapi1
      - fastapi2

  fastapi1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi1
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/rinha
      - INSTANCE_NAME=fastapi1
    depends_on:
      - db
      - redis
    ports:
      - "8001:8000"  # mapeando 8000 do container para 8001 localhost (apenas para debug)

  fastapi2:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi2
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/rinha
      - INSTANCE_NAME=fastapi2
    depends_on:
      - db
      - redis
    ports:
      - "8002:8000"


  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  db_data:
